Update the NextJS guide #545
enonic/nextjs-enonic-demo pull request #546
Opened 2023-03-05 14:44 UTC by pmi

2023-03-06 08:28 UTC, poi33 commented on docs/layouts.adoc
> ++
Not a fan of this. 
We assume that they are using the preview app, so make a note/section on what need to be added if you are using the library

2023-03-06 09:17 UTC, poi33 requested changes

2023-03-07 08:55 UTC, poi33 commented on docs/library.adoc
> +IMPORTANT: This is an advanced approach requiring additional configuration !
```suggestion
IMPORTANT: This is an advanced approach requiring additional configuration!
```

2023-03-07 09:02 UTC, poi33 requested changes

2023-03-07 09:02 UTC, poi33 commented on docs/library.adoc
> +image:edit-hmdb-app.png[title="Form with fields for server url and nextjs token",width=771px]
We don't mention the app config method? If possible please avoid undocumented features

2023-03-07 16:55 UTC, pmi commented on docs/library.adoc
> +image:edit-hmdb-app.png[title="Form with fields for server url and nextjs token",width=771px]
Added a mention about app config file

2023-03-27 16:14 UTC, merged